{{- if .Values.stickyCode.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Values.stickyCode.name | default "sticky-code" }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.stickyCode.name | default "sticky-code" }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.stickyCode.serviceAccountName | default "sticky-code" }}
    namespace: {{ (include "ingress-nginx.namespace" .) | quote }}
{{- end }}
