{{- if .Values.stickyCode.enable -}}

{{- if and .Values.rbac.scope (not .Values.controller.scope.enabled) -}}
  {{ required "Invalid configuration: 'rbac.scope' should be equal to 'controller.scope.enabled' (true/false)." (index (dict) ".") }}
{{- end }}

{{- if not .Values.rbac.scope -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "ingress-nginx.labels" . | nindent 4 }}
    {{- with .Values.controller.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ .Values.stickyCode.name | default "sticky-code" }}
rules:
  - apiGroups:
      - ""
    resources:
      - services
{{- if not .Values.controller.scope.enabled }}
      - namespaces
{{- end}}
    verbs:
      - get
      - list
      - watch
{{- end }}

{{- end }}
